sonar.projectKey=patriciamrs_PFC-ComparativoLLMs-aberto-propriet-rio
sonar.projectName=PFC-ComparativoLLMs-aberto-proprietario
sonar.projectVersion=1.0
sonar.organization=patriciamrs
sonar.sources=codigos

sonar.sourceEncoding=UTF-8